<a href="https://colab.research.google.com/github/RocioRodriguez13/Data-Science-Ingenias-2025/blob/main/Notebook_7__Rodriguez_Rocio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Programa Ingenias+ Data Science

## Trabajando con Pandas

1) Importa las librerias requeridas: `Pandas` y `NumPy`.  

Una buena practica a la hora de escribir codigo es de comentar siempre que estoy haciendo (usando `#`) en la linea anterior. Por mas obvio que parezca lo que voy a hacer, puede ser que tenga que compartir el documento con otras personas y no sepan que quise hacer en cada linea. O que yo mismo lea el codigo tiempo despues y no recuerde porque lo hice.

In [28]:
import pandas as pd
import numpy as np

2) Lee el archivo csv `life_expectancy_data` usando `pandas`. Guardalo en una variable llamada `expvida`.

In [4]:
# Leo los datos en un DataFrame
expvida = pd.read_csv('/Life_Expectancy_Data.csv')

In [6]:
expvida

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263,62,0.01,71.279624,65,1154,...,6,8.16,65,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271,64,0.01,73.523582,62,492,...,58,8.18,62,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268,66,0.01,73.219243,64,430,...,62,8.13,64,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272,69,0.01,78.184215,67,2787,...,67,8.52,67,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275,71,0.01,7.097109,68,3013,...,68,7.87,68,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1644,Zimbabwe,2004,Developing,44.3,723,27,4.36,0.000000,68,31,...,67,7.13,65,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
1645,Zimbabwe,2003,Developing,44.5,715,26,4.06,0.000000,7,998,...,7,6.52,68,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
1646,Zimbabwe,2002,Developing,44.8,73,25,4.43,0.000000,73,304,...,73,6.53,71,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
1647,Zimbabwe,2001,Developing,45.3,686,25,1.72,0.000000,76,529,...,76,6.16,75,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
1648,Zimbabwe,2000,Developing,46.0,665,24,1.68,0.000000,79,1483,...,78,7.10,78,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

3) ¿Que tipo de estructura de datos contiene la variable `expvida`?

In [7]:
# Obtengo el tipo de estructura de datos
type(expvida)

pandas.core.frame.DataFrame

4) ¿Cuantas filas y columnas tiene `expvida`?

In [8]:
# Uso .shape para obtener cantidad de filas y columnas
expvida.shape

(1649, 22)

**Numero de filas**: 1642

**Numero de columnas**:22

5) ¿Cual es el nombre de las columnas contenidas en `expvida`?

In [23]:
# Obtengo el nombre de las columnas

expvida.columns

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

6) Inspecciona las primeras 10 filas de `expvida`

In [10]:
# Inspecciono las primeras filas
expvida.head(10)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263,62,0.01,71.279624,65,1154,...,6,8.16,65,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271,64,0.01,73.523582,62,492,...,58,8.18,62,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268,66,0.01,73.219243,64,430,...,62,8.13,64,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272,69,0.01,78.184215,67,2787,...,67,8.52,67,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275,71,0.01,7.097109,68,3013,...,68,7.87,68,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
5,Afghanistan,2010,Developing,58.8,279,74,0.01,79.679367,66,1989,...,66,9.20,66,0.1,553.328940,2883167.0,18.4,18.4,0.448,9.2
6,Afghanistan,2009,Developing,58.6,281,77,0.01,56.762217,63,2861,...,63,9.42,63,0.1,445.893298,284331.0,18.6,18.7,0.434,8.9
7,Afghanistan,2008,Developing,58.1,287,80,0.03,25.873925,64,1599,...,64,8.33,64,0.1,373.361116,2729431.0,18.8,18.9,0.433,8.7
8,Afghanistan,2007,Developing,57.5,295,82,0.02,10.910156,63,1141,...,63,6.73,63,0.1,369.835796,26616792.0,19.0,19.1,0.415,8.4
9,Afghanistan,2006,Developing,57.3,295,84,0.03,17.171518,64,1990,...,58,7.43,58,0.1,272.563770,2589345.0,19.2,19.3,0.405,8.1

7) Y ahora las 10 ultimas.

In [11]:
# Inspecciono las ultimas filas
expvida.tail(10)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
1639,Zimbabwe,2009,Developing,50.0,587,30,4.64,1.040021,73,853,...,69,6.26,73,18.1,65.824121,1381599.0,7.5,7.4,0.419,9.9
1640,Zimbabwe,2008,Developing,48.2,632,30,3.56,20.843429,75,0,...,75,4.96,75,20.5,325.678573,13558469.0,7.8,7.8,0.421,9.7
1641,Zimbabwe,2007,Developing,46.6,67,29,3.88,29.814566,72,242,...,73,4.47,73,23.7,396.998217,1332999.0,8.2,8.2,0.414,9.6
1642,Zimbabwe,2006,Developing,45.4,7,28,4.57,34.262169,68,212,...,71,5.12,7,26.8,414.796232,13124267.0,8.6,8.6,0.408,9.5
1643,Zimbabwe,2005,Developing,44.6,717,28,4.14,8.717409,65,420,...,69,6.44,68,30.3,444.765750,129432.0,9.0,9.0,0.406,9.3
1644,Zimbabwe,2004,Developing,44.3,723,27,4.36,0.000000,68,31,...,67,7.13,65,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
1645,Zimbabwe,2003,Developing,44.5,715,26,4.06,0.000000,7,998,...,7,6.52,68,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
1646,Zimbabwe,2002,Developing,44.8,73,25,4.43,0.000000,73,304,...,73,6.53,71,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
1647,Zimbabwe,2001,Developing,45.3,686,25,1.72,0.000000,76,529,...,76,6.16,75,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
1648,Zimbabwe,2000,Developing,46.0,665,24,1.68,0.000000,79,1483,...,78,7.10,78,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

8) ¿Que tipos de datos contiene cada una de las columnas de `expvida`?

In [12]:
# Tipo de datos en cada columna
expvida.dtypes

Country                             object
Year                                 int64
Status                              object
Life expectancy                    float64
Adult Mortality                      int64
infant deaths                        int64
Alcohol                            float64
percentage expenditure             float64
Hepatitis B                          int64
Measles                              int64
 BMI                               float64
under-five deaths                    int64
Polio                                int64
Total expenditure                  float64
Diphtheria                           int64
 HIV/AIDS                          float64
GDP                                float64
Population                         float64
 thinness  1-19 years              float64
 thinness 5-9 years                float64
Income composition of resources    float64
Schooling                          float64
dtype: object

9) ¿Hay valores faltantes en alguna de las columnas de `expvida`?

In [15]:
# Obtengo la cantidad de datos faltantes en cada columna
expvida.isnull().sum()

Country                            0
Year                               0
Status                             0
Life expectancy                    0
Adult Mortality                    0
infant deaths                      0
Alcohol                            0
percentage expenditure             0
Hepatitis B                        0
Measles                            0
 BMI                               0
under-five deaths                  0
Polio                              0
Total expenditure                  0
Diphtheria                         0
 HIV/AIDS                          0
GDP                                0
Population                         0
 thinness  1-19 years              0
 thinness 5-9 years                0
Income composition of resources    0
Schooling                          0
dtype: int64

10) Selecciona el maximo de datos faltantes. Calcula que porcentaje de los datos representan los datos faltantes.

In [18]:
# Obtengo el maximo valor de datos faltantes y lo guardo en la variable masnan
faltantes = expvida.isnull().sum()
masnam = faltantes.max()
columna_mas_faltantes = faltantes.idxmax()
porcentaje = (masnam / len(expvida)) * 100

print(f"Columna con más datos faltantes: {columna_mas_faltantes}")
print(f"Cantidad de datos faltantes: {masnam}")
print(f"Porcentaje que representan: {porcentaje:}%")

Columna con más datos faltantes: Country
Cantidad de datos faltantes: 0
Porcentaje que representan: 0.0%

In [20]:
# Obtengo la cantidad de filas total y divido el maximo valor de datos faltantes por este numero
# y lo multiplico por 100

cantidad_filas_total = len(expvida)
porcentaje_datos_faltantes = (masnam / cantidad_filas_total) * 100

In [21]:
# Imprimo el maximo porcentaje de datos faltantes. Uso f-strings.

print(f"El porcentaje máximo de datos faltantes es: {porcentaje_datos_faltantes:.2f}%")

El porcentaje máximo de datos faltantes es: 0.00%

- str.format()
- Template Class
- f-strings

#### Ahora vamos a realizar algunos calculos y manipulaciones sobre las columnas.

Una función útil para este fin es: `.rename()`. Y podemos utilizarla de la siguiente manera: Si `df` es mi DataFrame y quiero renombrar la columna `columna` como `columna1`, y la columna `columna2` como `columna3`, utilizo la siguiente sintaxis:
  
`df.rename(columns={"columna": "columna1", "columna2": "columna3"}, inplace=True)`

11) Renombra la columna 'Life expectancy ' como 'life_expectancy', ' BMI ' como 'bmi' y ''Measles ' como 'measles'. No olvides de usar `inplace` para modificar el DataFrame original. Luego chequea que el cambio se haya hecho correctamente.

In [24]:
# Renombro columnas del DataFrame
expvida.rename(columns={"Life expectancy ": "life_expectancy", " BMI ": "bmi", "Measles ": "measles"}, inplace=True)

In [25]:
# Chequeo que se hayan reemplazado correctamente
expvida.columns

Index(['Country', 'Year', 'Status', 'life_expectancy', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'measles', 'bmi', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

12) ¿Cual es el promedio de expectativa de vida (Life expectancy) en general?

In [26]:
# Obtengo el promedio de la columna
promedio_en_general=expvida['life_expectancy'].mean()
print(f"El promedio de la columna 'life_expectancy' es: {promedio_en_general}")

El promedio de la columna 'life_expectancy' es: 69.3023044269254

13) ¿Cual es el promedio de expectativa de vida (Life expectancy) por país?

In [27]:
# Obtengo el promedio por pais
promedio_por_pais = expvida.groupby('Country')['life_expectancy'].mean()
print(promedio_por_pais)

Country
Afghanistan    58.193750
Albania        75.156250
Algeria        74.209091
Angola         50.675000
Argentina      75.238462
                 ...
Uruguay        76.013333
Uzbekistan     68.046154
Vanuatu        71.346667
Zambia         57.250000
Zimbabwe       49.386667
Name: life_expectancy, Length: 133, dtype: float64

14) ¿Cual es la expectativa de vida mas alta y mas baja? Usa la funcion de pandas y la funcion de NumPy y compara el resultado. ¿Que paises tienen esas expectativas de vida?

In [29]:
# Maxima expectativa de vida usando numpy

max_exp_con_np = np.max(expvida['life_expectancy'])
print(f"La máxima expectativa de vida usando NumPy es: {max_exp_con_np}")

La máxima expectativa de vida usando NumPy es: 89.0

In [30]:
# Maxima expectativa de vida usando pandas
max_exp_pd = expvida['life_expectancy'].max()
print(f"La máxima expectativa de vida usando Pandas es: {max_exp_pd}")

La máxima expectativa de vida usando Pandas es: 89.0

In [31]:
# Minima expectativa de vida usando numpy
minima_exp_con_np = np.min(expvida['life_expectancy'])
print(f"La mínima expectativa de vida usando NumPy es: {minima_exp_con_np}")

La mínima expectativa de vida usando NumPy es: 44.0

In [32]:
# Minima expectativa de vida usando pandas
minima_exp_con_pandas = expvida['life_expectancy'].min()
print(f"La mínima expectativa de vida usando Pandas es: {minima_exp_con_pandas}")

La mínima expectativa de vida usando Pandas es: 44.0

In [33]:
# Muestro los resultados maximos
print(max_exp_con_np)
print(max_exp_pd)

89.0
89.0

In [34]:
# Muestro los resultados minimos
print(minima_exp_con_np)
print(minima_exp_con_pandas)

44.0
44.0

In [35]:
# Filtro las columnas para mostrar solo las filas que tengan valor
# igual al maximo

filtro_columnas_max = expvida[expvida['life_expectancy'] == max_exp_con_np]
print(filtro_columnas_max)

       Country  Year      Status  life_expectancy  Adult Mortality  \
148    Belgium  2014   Developed             89.0               76
532     France  2008  Developing             89.0               88
533     France  2007  Developing             89.0               89
566    Germany  2014   Developed             89.0               69
731      Italy  2004   Developed             89.0               66
1217  Portugal  2014   Developed             89.0               78
1383     Spain  2007   Developed             89.0               72

      infant deaths  Alcohol  percentage expenditure  Hepatitis B  measles  \
148               0    12.60             7163.348923           98       70
532               3    11.90             7002.785925           47      604
533               3    12.20               64.737149           42       39
566               2    11.03              941.756291           88      443
731               2     8.98             4270.914882           96      599
1217              0     9.88              271.254553           98        0
1383              2    11.05              510.932701           96      267

      ...  Polio  Total expenditure  Diphtheria    HIV/AIDS          GDP  \
148   ...     99               1.59           99        0.1  47439.39684
532   ...     98               1.57           98        0.1  45413.65710
533   ...     99               1.45           98        0.1    416.58397
566   ...     94              11.30           95        0.1   4792.65288
731   ...     97               8.49           94        0.1  31174.56118
1217  ...     98               9.50           98        0.1   2277.53613
1383  ...     96               8.36           96        0.1   3279.41400

      Population   thinness  1-19 years   thinness 5-9 years  \
148     112957.0                    1.0                  1.0
532    6437499.0                    0.6                  0.6
533    6416229.0                    0.6                  0.6
566      89825.0                    1.1                  1.1
731   57685327.0                    0.5                  0.5
1217     14162.0                    0.7                  0.5
1383   4522683.0                    0.6                  0.5

      Income composition of resources  Schooling
148                             0.890       16.3
532                             0.877       16.1
533                             0.873       16.1
566                             0.920       17.0
731                             0.846       15.6
1217                            0.837       16.8
1383                            0.849       16.0

[7 rows x 22 columns]

In [36]:
# Filtro las columnas para mostrar solo las filas que tengan valor
# igual al minimo

filtro_columnas_min = expvida[expvida['life_expectancy'] == minima_exp_con_np]
print(filtro_columnas_min)

    Country  Year      Status  life_expectancy  Adult Mortality  \
910  Malawi  2002  Developing             44.0               67

     infant deaths  Alcohol  percentage expenditure  Hepatitis B  measles  \
910             46      1.1                3.885395           64       92

     ...  Polio  Total expenditure  Diphtheria    HIV/AIDS        GDP  \
910  ...     79               4.82           64       24.7  29.979898

     Population   thinness  1-19 years   thinness 5-9 years  \
910   1213711.0                    7.7                  7.6

     Income composition of resources  Schooling
910                            0.388       10.4

[1 rows x 22 columns]

15) ¿Cuantas categorias encontramos en la columna "Status"? _**Pista**_: Lee acerca de la función [unique()](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.unique.html?highlight=unique#pandas.Series.unique)

In [37]:
# Obtengo los valores unicos de la columna status
valores_unicos = expvida['Status'].unique()
print(valores_unicos)

['Developing' 'Developed']

16) ¿Cuantos paises se ubican en cada una de esas categorias de "Status"? _**Pista**_: Lee acerca de la función [value_counts()](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html)

In [38]:
# Cuento cuantos valores hay de cada categoria
categorias_paises = expvida['Status'].value_counts()
print(categorias_paises)

Status
Developing    1407
Developed      242
Name: count, dtype: int64

18) ¿Cuantos paises presentaron algun caso de Sarampion (**Measles**) en el 2015? **_Pista_**: Lee acerca de la función [.count()](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.count.html?highlight=count#pandas.DataFrame.count)

In [40]:
# Cuento cuantas filas tienen valores distintos de cero
casos_sarampion = expvida[(expvida['measles'] != 0) & (expvida['Year'] == 2015)].count()
print(casos_sarampion)

Country                            2
Year                               2
Status                             2
life_expectancy                    2
Adult Mortality                    2
infant deaths                      2
Alcohol                            2
percentage expenditure             2
Hepatitis B                        2
measles                            2
bmi                                2
under-five deaths                  2
Polio                              2
Total expenditure                  2
Diphtheria                         2
 HIV/AIDS                          2
GDP                                2
Population                         2
 thinness  1-19 years              2
 thinness 5-9 years                2
Income composition of resources    2
Schooling                          2
dtype: int64